### ISSUE TITLE
same result each run

### ISSUE THREAD

**Issue by L10N37** [jeanthom/ESP32-APLL-cal#1]
[Running] cd "p:\ESP32_APLL_CALC\" && g++ APLLCALC_ESP32.cpp -o APLLCALC_ESP32 && "p:\ESP32_APLL_CALC\"APLLCALC_ESP32
f=5303030.3 Hz, ∆f=5302976.6 Hz (relative: 9876444.4640%)
sdm0=0, sdm1=192, sdm2=4, odiv=31

[Done] exited with code=0 in 6.839 seconds

I get this each time it's run in the window via VSCode? It doesn't matter what i set the target freq to.

**Comment by L10N37** [comment]
Uninstalled code runner and re-installed and it's working now.

**Comment by jeanthom** [comment]
Hmm weird, I don't use VSCode runner so I can't really help you here... I'm glad you found a solution!
